#!/usr/bin/python
import os
import time
import subprocess
parameter = int(input("Enter parameter: "))
#p = sub.Popen(('python', 'test.py', ''), stdout=sub.PIPE)
sudo_test = 'cubieboard'
command = 'login_sudo_success'
os.system('echo %s %s ' % (sudo_test, command))
blueled_trigger = 'sudo sh -c "echo none > /sys/class/leds/blue:ph21:led1/trigger"'
greenled_trigger = 'sudo sh -c "echo none > /sys/class/leds/green:ph07:led4/trigger"'
blueled_on = 'sudo sh -c "echo 1 > /sys/class/leds/blue:ph21:led1/brightness"'
blueled_off = 'sudo sh -c "echo 0 > /sys/class/leds/blue:ph21:led1/brightness"'
greenled_on = 'sudo sh -c "echo 1 > /sys/class/leds/green:ph07:led4/brightness"'
greenled_off = 'sudo sh -c "echo 0 > /sys/class/leds/green:ph07:led4/brightness"'
os.system(blueled_trigger)
os.system(greenled_trigger)
os.system(blueled_off)
loop_count = 0;

while(True):

        if loop_count <= parameter:
                os.system(blueled_on)
                print(loop_count)
                time.sleep(0.5)
                os.system(blueled_off)
                os.system(greenled_on)
                print(loop_count)
                time.sleep(0.5)
                os.system(greenled_off)
                loop_count = loop_count + 1
                print(loop_count)
        else:
                os.system(blueled_off)
                os.system(greenled_off)
                break


